config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :projets, only: [:create, :index, :new]
  get  'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/projet.rb
class Projet < ApplicationRecord

  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :description, presence:true
  validates :url, presence: true
  validates :stack, presence: true
  validates :date, presence: true
  validates :host, presence: true
  validates :github, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about ]

  def home
    @projets = Projet.all
  end
  
  def about
  end

end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @projets = Projet.all
  end

  def new
    @projet = Projet.new
  end

  def create
    @projet = Projet.new(projet_params)
    @projet.stack.shift
    if @projet.save!
      redirect_to projets_path(@projet)
    else
      raise
      render :new
    end
  end

  private
  def projet_params
    params.require(:projet).permit(:name, :description, :date, :github, :host, :photo, :url, :stack => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio d'auriane gregoire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/png" href="https://res.cloudinary.com/ddw7wju1q/image/upload/v1617729806/flaticon_zb59xm.svg" />
    <meta name="description" content="Découvrez le portfolio d'Auriane Grégoire, fullstack dévelppeuse web spécialisée en Ruby on rails.">

    <meta property="og:title" content="Portfolio d'auriane gregoire" />
    <meta property="og:image" content="https://res.cloudinary.com/ddw7wju1q/image/upload/v1617729806/meta-img_k6esyt.png"/>
    <meta property="og:description" content="Découvrez le portfolio d'Auriane Grégoire, fullstack dévelppeuse web spécialisée en Ruby on rails."/>
    <meta property="og:url" content="http://www.auriane-gregoire.com"/>
    <meta property="og:type" content="website" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about-header">
  <div class ="info-left">
    <h1><span>Auriane Grégoire</span></h1>
    <h2>Fullstack developpeuse</h2>
    <div class='contact-head'>
      <a href="https://github.com/Auriane-grg" target="_blanck"><i class="fab fa-github-square"></i></a>
      <a href="https://www.linkedin.com/in/augregoire/" target="_blanck"><i class="fab fa-linkedin-in"></i></a>
      <a href="mailto:auriane.gregoire@gmail.com" target="_blanck"><i class="fas fa-paper-plane"></i></a>
    </div>
  </div>
  <div class='photo-right'>
    <%= cl_image_tag("auriane_tb2aww") %>
  </div>
</div>

<div id="about-me">
  <p>Passionnée et curieuse, <b>je code des applications sous Ruby on Rails, Java, et Javascript</b>. Je m'efforce de les rendre aussi faciles d'utilisation que design !</p>
  <p>Cette double casquette me provient de mes expériences passées en tant que Product Owner, durant lesquelles j'ai commencé à me passionner pour le code. Cela m'a également appris l'importance de délivrer petit à petit un <b>produit dont l'UX et l'UI ont été pensées, testées</b> et validées auparavant. Les mots "scrum", "test", "user stories" et "backlog" ne me font donc pas peur.</p>
  <p>Aujourd'hui, <b>je souhaite relever de nouveaux défis techniques et créatifs au sein d'une nouvelle équipe !</b></p>
</div>

<div class='btn-inside'>
  <%= link_to 'VOIR MES PROJETS', projets_path, class:'btn'%>
</div>

<div id="skills">
  <%= cl_image_tag("rails_zrus9h") %>
  <%= cl_image_tag("ruvy_fwnuyr") %>  
  <%= cl_image_tag("sql_dbnppw") %>
  <%= cl_image_tag("js_alec8h") %>
  <%= cl_image_tag("css_fxuitt") %>
  <%= cl_image_tag("html_cmlh6k") %>
  <%= cl_image_tag("git_ta1am6") %>

</div>

app/views/pages/home.html.erb
<div id="home-header">
  <div class ="info-left">
    <p>Bonjour, je suis</p>
    <h1><span> Auriane Grégoire</span></h1>
    <div class='photo-profile-mob'>
      <%= cl_image_tag("auriane_tb2aww") %>
    </div>
    <h2>Je suis Fullstack développeuse</h2>
    <div class='lang-head'>
      <%= cl_image_tag("rails_qg59oc") %>
      <%= cl_image_tag("RUBY_wfuhrq") %>
      <%= cl_image_tag("js_uoiccw") %>
      <%= cl_image_tag("sql_qidann") %>
      <%= cl_image_tag("css_blof29") %>
      <%= cl_image_tag("html_opud0k") %>
    </div>
  </div>
  <div class='photo-right'>
    <%= cl_image_tag("auriane_tb2aww") %>
  </div>

  
</div>
<div class="projects">
  <% @projets.each do  |projet| %>
    <% if projet.id.even?%>
      <div class="projet">
        <div class='mob-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
        <div class="projet-left-info">
          <h2><%= projet.name %></h2>
          <p class='date'><%= projet.date %></p>
          <p class="description"><%= projet.description %></p>
          <% p = projet.name.partition(" ").first %>
          <%= link_to "EN SAVOIR PLUS", projets_path(anchor: p), class:'btn' %>
        </div>
        <div class='projet-right-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
      </div>
    <% else %>
      <div class="projet">
        <div class='mob-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
        <div class='projet-left-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
        <div class="projet-right-info">
          <h2><%= projet.name %></h2>
          <p class="description"><%= projet.description %></p>
          <%= link_to "EN SAVOIR PLUS", projets_path, class:'btn' %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projets/index.html.erb
<div id="projects">
  <% @allprojets = @projets.order("id ASC") %>
  <% @allprojets.each do  |projet| %>
    <% if projet.id.even? %>
      <div class="projet" id="<%= projet.name.partition(" ").first %>">
          <div class='mob-photo'>
            <%= cl_image_tag projet.photo.key %>
          </div>
        <div class="projet-left-info">
          <h2><%= projet.name %></h2>
          <p class='date'><%= link_to projet.github, target: "_blank" do %><i class="fab fa-github-square github-link"></i><% end %><%= projet.date %></p>
          <p class="description"><%= projet.description %></p>
          <p class='hebergement'><b>App hébergée sur : </b><%= projet.host %></p>
          <p><b>Database :</b> postgresql</p>
          <p><b>Stack : </b></p>
          <ul class='stack'>
            <% projet.stack.each do |s| %>
              <li><%= s %> </li>
            <% end %>
          </ul>
          <a href="<%= projet.url %>" target='blank' class='btn'>VISITER L'APP</a>
        </div>
        <div class='projet-right-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
      </div>
    <% else %>
      <div class="projet" id="<%= projet.name.partition(" ").first %>">
        <div class='projet-left-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
        <div class='mob-photo'>
          <%= cl_image_tag projet.photo.key %>
        </div>
        <div class="projet-right-info">
          <h2><%= projet.name %></h2>
          <p class='date'><%= link_to projet.github, target: "_blank" do %><i class="fab fa-github-square github-link"></i><% end %><%= projet.date %></p>
          <p class="description"><%= projet.description %></p>
          <p class='hebergement'><b>App hébergée sur : </b><%= projet.host %></p>
          <p><b>Database :</b> postgresql</p>
          <p><b>Stack : </b></p>
          <ul class='stack'>
            <% projet.stack.each do |s| %>
              <li><%= s %> </li>
            <% end %>
          </ul>
          <a href="<%= projet.url %>" target='blank' class='btn'>VISITER L'APP</a>
        </div>
      </div>

    <% end %>
  <% end %>
</div>
<%# 

        <div class='mob-photo'>
          <%= cl_image_tag projet.photo.key %>
        <%# </div> %>

app/views/projets/new.html.erb
    <%= simple_form_for(@projet) do |f| %>
        <%= f.input :name %>
        <%= f.input :date %>
        <%= f.input :description %>
        <%= f.input :host %>
        <%= f.input :url %>
        <%= f.input :github %>
        <%= f.input :stack, :collection => ["ruby on rails", "javascript", "css", "html"], :input_html => { multiple: true } %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class:'btn' %>
      <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="navbar" class="nav-top">
  <div id="my-links">
    <a href="https://github.com/Auriane-grg" target="_blanck"><i class="fab fa-github-square"></i></a>
    <a href="https://www.linkedin.com/in/augregoire/" target="_blanck"><i class="fab fa-linkedin-in"></i></a>
    <a href="mailto:auriane.gregoire@gmail.com" target="_blanck"><i class="fas fa-paper-plane"></i></a>
    </div>
  <div id="pages">
    <%= link_to "Home", root_path %>
    <%= link_to "Projets", projets_path %>
    <%= link_to "Auriane",  pages_about_path %>
  </div>
</div>